import { ArrowUpRight, ArrowRight, Plus, MessageSquare, BookOpen, FileText, Zap, Layers3, Upload, Database, Server, Cpu, CircleHelp, Sparkles, ChevronRight, Check, Clock3, Code2, Network } from 'lucide-react';
import type { Bootstrap, Health, KnowledgeBase, Page } from './types';
import { Badge, KBIcon, PageHeading, SectionHeading, TrendChart } from './ui';
import { number, relativeTime } from './api';

export default function Dashboard({ data, health, navigate, onCreate, onUpload, onOpenKB }: { data: Bootstrap; health: Health | null; navigate: (page: Page) => void; onCreate: () => void; onUpload: () => void; onOpenKB: (kb: KnowledgeBase) => void }) {
  const metrics = [
    { label: '知识库总数', value: String(data.knowledgeBases.length).padStart(2, '0'), unit: '个', icon: BookOpen, tone: 'orange', foot: '构建属于团队的知识网络', change: `${data.knowledgeBases.filter(k => k.status === 'ready').length} 个已就绪` },
    { label: '已索引文档', value: number(data.documents.filter(d => d.status === 'ready').length), unit: '份', icon: FileText, tone: 'blue', foot: `${number(data.documents.reduce((s, d) => s + d.chunkCount, 0))} 个知识片段`, change: '持续积累中' },
    { label: '累计问答次数', value: number(data.stats.queries), unit: '次', icon: MessageSquare, tone: 'purple', foot: '较上一统计周期', change: `+${data.stats.queryChange}%` },
    { label: '平均响应时间', value: data.stats.latency > 20 ? (data.stats.latency / 1000).toFixed(2) : data.stats.latency.toFixed(2), unit: '秒', icon: Zap, tone: 'green', foot: '快速检索，即时响应', change: '体验流畅' },
  ];
  return <div className="dashboard page-enter"><PageHeading eyebrow="YOUR KNOWLEDGE, CONNECTED" title="工作空间概览" description="连接分散的知识，让每一次提问都有据可依。" action={<><button className="button" onClick={() => navigate('chat')}><Sparkles size={16} />体验 AI 问答</button><button className="button primary" onClick={onCreate}><Plus size={17} />新建知识库</button></>} />
    <div className="metrics-grid">{metrics.map((m, i) => <div className="metric-card" key={m.label}><div className="metric-top"><span>{m.label}</span><span className={`metric-icon ${m.tone}`}><m.icon size={18} strokeWidth={1.7} /></span></div><div className="metric-value">{m.value}<span>{m.unit}</span></div><div className="metric-bottom"><span className={`metric-change ${i === 2 ? 'green-text' : ''}`}>{i === 2 ? <ArrowUpRight size={13} /> : <span className="tiny-dot" />}{m.change}</span><span>{m.foot}</span></div></div>)}</div>
    <div className="insights-grid"><TrendChart trend={data.stats.trend} /><div className="panel status-panel"><div className="panel-heading"><h2>系统运行状态</h2><Badge tone={health?.ai === 'up' ? 'green' : 'amber'}>{health?.ai === 'up' ? '运行正常' : '连接中'}</Badge></div><div className="system-intro">双引擎协同，让知识服务稳定在线</div><div className="system-services">{[
      { icon: Server, label: '业务服务', detail: 'Spring Boot', state: health?.business === 'up' ? '在线' : '连接中', online: health?.business === 'up' },
      { icon: Code2, label: 'AI 编排服务', detail: 'FastAPI', state: health?.ai === 'up' ? '在线' : '连接中', online: health?.ai === 'up' },
      { icon: Database, label: '知识检索引擎', detail: 'BM25 + TF-IDF', state: health?.ai === 'up' ? '就绪' : '连接中', online: health?.ai === 'up' },
      { icon: Cpu, label: '模型网关', detail: data.mode === 'connected' ? 'OpenAI Compatible' : '本地检索模式', state: data.mode === 'connected' ? '已连接' : '本地', online: data.mode === 'connected' },
    ].map(s => <div className="service-row" key={s.label}><div className="service-symbol"><s.icon size={17} strokeWidth={1.6} /></div><div className="service-name"><strong>{s.label}</strong><span>{s.detail}</span></div><span className={`service-state ${s.online ? 'online' : 'local'}`}><i />{s.state}</span></div>)}</div><button className="system-footer" onClick={() => navigate('settings')}><span><Network size={14} /> 查看服务与模型配置</span><ChevronRight size={15} /></button></div></div>
    <section className="knowledge-section"><SectionHeading title="我的知识库" subtitle="沉淀团队经验，连接每一份有价值的知识" action={<button className="text-button" onClick={() => navigate('knowledge')}>查看全部 <ArrowRight size={15} /></button>} /><div className="kb-grid">{data.knowledgeBases.slice(0, 3).map(kb => <KnowledgeCard key={kb.id} kb={kb} onClick={() => onOpenKB(kb)} />)}</div></section>
    <div className="bottom-grid"><div className="panel activity-panel"><div className="panel-heading"><h2>最近动态</h2><button className="text-button" onClick={() => navigate('analytics')}>全部活动 <ArrowRight size={14} /></button></div><div className="activity-list">{data.activities.slice(0, 4).map((a, i) => <div className="activity-item" key={a.id}><div className={`activity-icon ${a.type === 'chat' ? 'purple' : a.type === 'create' ? 'orange' : 'blue'}`}>{a.type === 'chat' ? <MessageSquare size={15} /> : a.type === 'create' ? <BookOpen size={15} /> : a.type === 'index' ? <Check size={15} /> : <Upload size={15} />}</div><div className="activity-copy"><strong>{a.title}</strong><p>{a.description}</p></div><time>{relativeTime(a.time)}</time>{i < 3 && <span className="activity-line" />}</div>)}</div></div><div className="quick-start"><div className="quick-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="orbit-icon orbit-book"><BookOpen size={19} /></span><span className="orbit-icon orbit-spark"><Sparkles size={22} /></span><span className="orbit-dot" /><div className="orbit-center"><Layers3 size={35} strokeWidth={1.3} /></div></div><span className="quick-eyebrow">FROM KNOWLEDGE TO POSSIBILITY</span><h2>好答案，始于好知识。</h2><p>上传第一份新文档，让团队的经验<br />成为触手可及的智慧。</p><button className="button" onClick={onUpload}><Upload size={15} />导入文档<ArrowUpRight size={15} /></button><div className="quick-hint"><CircleHelp size={12} /> 支持 PDF、Word、Markdown 等格式</div></div></div>
    <div className="page-footer"><span><span className="footer-dot" /> 所有知识，有序连接。</span><span>知序 Knobase <span className="footer-sep">/</span> 企业 AI 知识中枢</span></div>
  </div>;
}

export function KnowledgeCard({ kb, onClick }: { kb: KnowledgeBase; onClick: () => void }) { return <button className="knowledge-card" onClick={onClick}><div className="kb-card-top"><KBIcon kb={kb} /><Badge tone={kb.status === 'ready' ? 'green' : 'amber'}>{kb.status === 'ready' ? '已就绪' : '索引中'}</Badge></div><h3>{kb.name}<ArrowUpRight size={16} /></h3><p className="kb-description">{kb.description}</p><div className="kb-tags">{kb.tags.slice(0, 3).map(tag => <span key={tag}>{tag}</span>)}</div><div className="kb-card-bottom"><span><FileText size={13} />{kb.documentCount} 份文档<span className="dot-sep">·</span><Layers3 size={13} />{number(kb.chunkCount)} 片段</span><span><Clock3 size={12} />{relativeTime(kb.updatedAt)}</span></div></button>; }
